require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")

-- require("user.ale")
-- require("user.coc")
-- require("user.coc-svelte")
-- require("user.html5")
-- require("user.yats")
require("user.alpha")
require("user.autocommands")
require("user.autopairs")
require("user.bufferline")
require("user.cmp")
require("user.colorscheme")
require("user.comment")
-- require("user.context_filetype")
require("user.dapui")
require("user.gitsigns")
require("user.illuminate")
require("user.impatient")
require("user.indentblankline")
require("user.inlay-hints")
require("user.lsp")
require("user.lualine")
require("user.mini-indentscope")
require("user.neodev")
require("user.notify")
require("user.nvimtree")
require("user.project")
require("user.rust-tools")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
require("user.trouble")
-- require("user.vim-javascript")
-- require("user.vim-prettier")
-- require("user.vim-svelte")
require("user.whichkey")
