{
  # Generated by `android-enforce --dump --dump-all` — the declared apps'
  # full current state: every runtime permission they hold, notification
  # access, the app ops that are explicitly granted and the link domains
  # that open in the app. Applying it is a no-op; it *is* the phone.
  permissions = {
    "ch.pocketpc.nearbyglasses" = {
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
    "ch.sbb.mobile.android.preview" = {
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.ACTIVITY_RECOGNITION" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
    "com.discord" = {
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
    };
    "com.eveningoutpost.dexdrip" = {
      "android.permission.health.READ_RESTING_HEART_RATE" = "allow";
      "android.permission.health.READ_ELEVATION_GAINED" = "allow";
      "android.permission.READ_CALL_LOG" = "allow";
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.health.READ_HEART_RATE_VARIABILITY" = "allow";
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.health.READ_HYDRATION" = "allow";
      "android.permission.health.READ_WHEELCHAIR_PUSHES" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.health.READ_DISTANCE" = "allow";
      "android.permission.health.WRITE_BLOOD_GLUCOSE" = "allow";
      "android.permission.health.READ_TOTAL_CALORIES_BURNED" = "allow";
      "android.permission.READ_EXTERNAL_STORAGE" = "allow";
      "android.permission.health.READ_NUTRITION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.READ_PHONE_STATE" = "allow";
      "android.permission.SEND_SMS" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.health.WRITE_NUTRITION" = "allow";
      "android.permission.BLUETOOTH_ADVERTISE" = "allow";
      "android.permission.health.READ_EXERCISE" = "allow";
      "android.permission.GET_ACCOUNTS" = "allow";
      "android.permission.health.READ_POWER" = "allow";
      "android.permission.health.READ_SLEEP" = "allow";
      "android.permission.health.READ_SPEED" = "allow";
      "android.permission.health.READ_STEPS" = "allow";
      "android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
      "android.permission.health.READ_HEIGHT" = "allow";
      "android.permission.health.READ_BLOOD_GLUCOSE" = "allow";
      "android.permission.ACTIVITY_RECOGNITION" = "allow";
      "android.permission.health.READ_FLOORS_CLIMBED" = "allow";
      "android.permission.health.READ_WEIGHT" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
      "android.permission.ACCESS_BACKGROUND_LOCATION" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
      "android.permission.health.READ_HEART_RATE" = "allow";
      "android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    };
    "com.termux" = {
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.READ_EXTERNAL_STORAGE" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
      "android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    };
    "com.termux.api" = {
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.READ_EXTERNAL_STORAGE" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
      "android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    };
    "com.ubs.Paymit.android" = {
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.WRITE_CONTACTS" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
    };
    "com.ubs.swidK2Y.android" = {
      "android.permission.CAMERA" = "allow";
    };
    "com.urbandroid.sleep" = {
      "android.permission.ACTIVITY_RECOGNITION" = "allow";
    };
    "com.whatsapp" = {
      "android.permission.READ_CALL_LOG" = "allow";
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.READ_PHONE_STATE" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.WRITE_CONTACTS" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.GET_ACCOUNTS" = "allow";
      "android.permission.RECORD_AUDIO" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
    };
    "com.x8bit.bitwarden" = {
      "android.permission.CAMERA" = "allow";
    };
    "de.mm20.launcher2.release" = {
      "android.permission.READ_CALENDAR" = "allow";
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
    };
    "me.kavishdevar.librepods" = {
      "android.permission.ANSWER_PHONE_CALLS" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.READ_PHONE_STATE" = "allow";
      "android.permission.BLUETOOTH_ADVERTISE" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
    "org.mozilla.firefox" = {
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.CAMERA" = "allow";
    };
    "tk.glucodata" = {
      "android.permission.NEARBY_WIFI_DEVICES" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.health.WRITE_BLOOD_GLUCOSE" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.BLUETOOTH_ADVERTISE" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
  };
  notifications = {
    "ai.polycam" = {
      enabled = false;
    };
    "app.deglaze.prod" = {
      enabled = false;
    };
    "app.linear" = {
      enabled = false;
    };
    "app.revanced.manager.flutter" = {
      enabled = true;
    };
    "app.sabre.wzsabre" = {
      enabled = false;
    };
    "app.secanda.www" = {
      enabled = false;
    };
    "ch.admin.swisstopo" = {
      enabled = false;
    };
    "ch.agov.accessapp" = {
      enabled = false;
    };
    "ch.bk.voteinfo" = {
      enabled = false;
    };
    "ch.medgate.threesixty.app" = {
      enabled = false;
    };
    "ch.migros.app" = {
      enabled = true;
    };
    "ch.pocketpc.nearbyglasses" = {
      enabled = true;
    };
    "ch.sbb.mobile.android.preview" = {
      enabled = true;
    };
    "ch.stadt.sg.moapp" = {
      enabled = false;
    };
    "ch.threema.app" = {
      enabled = false;
    };
    "com.Slack" = {
      enabled = false;
    };
    "com.Splitwise.SplitwiseMobile" = {
      enabled = false;
    };
    "com.app.tgtg" = {
      enabled = false;
    };
    "com.bitwarden.authenticator" = {
      enabled = false;
    };
    "com.cashyou" = {
      enabled = false;
    };
    "com.citypop.app" = {
      enabled = false;
    };
    "com.deniscerri.ytdl" = {
      enabled = false;
    };
    "com.dergoogler.mmrl" = {
      enabled = false;
    };
    "com.discord" = {
      enabled = true;
    };
    "com.emanuelef.remote_capture" = {
      enabled = false;
    };
    "com.eveningoutpost.dexdrip" = {
      enabled = true;
      listeners = [ "com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.services.UiBasedCollector" ];
    };
    "com.facebook.katana" = {
      enabled = false;
    };
    "com.facebook.pages.app" = {
      enabled = false;
    };
    "com.ghisler.android.TotalCommander" = {
      enabled = false;
    };
    "com.github.android" = {
      enabled = true;
    };
    "com.goodreads" = {
      enabled = false;
    };
    "com.google.android.apps.adm" = {
      enabled = false;
    };
    "com.google.android.apps.books" = {
      enabled = false;
    };
    "com.google.android.apps.chromecast.app" = {
      enabled = false;
    };
    "com.google.android.apps.docs.editors.docs" = {
      enabled = false;
    };
    "com.google.android.apps.docs.editors.sheets" = {
      enabled = false;
    };
    "com.google.android.apps.fitness" = {
      enabled = false;
    };
    "com.google.android.apps.healthdata" = {
      enabled = false;
    };
    "com.google.android.apps.magazines" = {
      enabled = false;
    };
    "com.google.android.apps.tasks" = {
      enabled = false;
    };
    "com.google.android.apps.translate" = {
      enabled = false;
    };
    "com.google.android.apps.walletnfcrel" = {
      enabled = true;
    };
    "com.google.android.apps.youtube.creator" = {
      enabled = false;
    };
    "com.google.android.verifier" = {
      enabled = false;
    };
    "com.instagram.android" = {
      enabled = false;
    };
    "com.instagram.barcelona" = {
      enabled = false;
    };
    "com.jndapp.cartoon.crayon.iconpack" = {
      enabled = false;
    };
    "com.knudge.me" = {
      enabled = false;
    };
    "com.lemon.lvoverseas" = {
      enabled = false;
    };
    "com.linkedin.android" = {
      enabled = false;
    };
    "com.marsvard.stickermakerforwhatsapp" = {
      enabled = false;
    };
    "com.mcdonalds.mobileapp" = {
      enabled = false;
    };
    "com.metrolist.music" = {
      enabled = true;
    };
    "com.microsoft.office.excel" = {
      enabled = true;
    };
    "com.microsoft.office.outlook" = {
      enabled = true;
    };
    "com.microsoft.office.word" = {
      enabled = true;
    };
    "com.microsoft.teams" = {
      enabled = false;
    };
    "com.nianticlabs.scaniverse" = {
      enabled = false;
    };
    "com.niksoftware.snapseed" = {
      enabled = false;
    };
    "com.nuvio.app" = {
      enabled = false;
    };
    "com.orailnoor.privatelm" = {
      enabled = false;
    };
    "com.revolut.revolut" = {
      enabled = false;
    };
    "com.rubenmayayo.lemmy" = {
      enabled = false;
    };
    "com.snapchat.android" = {
      enabled = false;
    };
    "com.stremio.one" = {
      enabled = false;
    };
    "com.sukisu.ultra" = {
      enabled = true;
    };
    "com.suno.android" = {
      enabled = false;
    };
    "com.tailscale.ipn" = {
      enabled = false;
    };
    "com.termux" = {
      enabled = true;
    };
    "com.termux.api" = {
      enabled = true;
      listeners = [ "com.termux.api/com.termux.api.apis.NotificationListAPI$NotificationService" ];
    };
    "com.ubs.Paymit.android" = {
      enabled = true;
    };
    "com.ubs.swidK2Y.android" = {
      enabled = false;
    };
    "com.urbandroid.sleep" = {
      enabled = true;
    };
    "com.valvesoftware.android.steam.community" = {
      enabled = false;
    };
    "com.watchguard.authpoint" = {
      enabled = false;
    };
    "com.whatsapp" = {
      enabled = true;
    };
    "com.x8bit.bitwarden" = {
      enabled = true;
    };
    "com.xda.sa2ration" = {
      enabled = false;
    };
    "dantotsu.downloadAddon" = {
      enabled = false;
    };
    "dantotsu.torrentAddon" = {
      enabled = false;
    };
    "de.komoot.android" = {
      enabled = false;
    };
    "de.mm20.launcher2.release" = {
      enabled = false;
      listeners = [ "de.mm20.launcher2.release/de.mm20.launcher2.notifications.NotificationService" ];
    };
    "dev.imranr.obtainium" = {
      enabled = false;
    };
    "droom.sleepIfUCan" = {
      enabled = false;
    };
    "io.element.android.x" = {
      enabled = false;
    };
    "io.ente.auth" = {
      enabled = false;
    };
    "io.keybase.ossifrage" = {
      enabled = false;
    };
    "me.kavishdevar.librepods" = {
      enabled = true;
    };
    "neth.iecal.curbox" = {
      enabled = false;
    };
    "org.adaway" = {
      enabled = false;
    };
    "org.mozilla.firefox" = {
      enabled = true;
    };
    "org.proninyaroslav.libretorrent" = {
      enabled = false;
    };
    "org.telegram.messenger" = {
      enabled = false;
    };
    "org.thoughtcrime.securesms" = {
      enabled = false;
    };
    "org.torproject.android" = {
      enabled = false;
    };
    "org.videolan.vlc" = {
      enabled = false;
    };
    "tk.glucodata" = {
      enabled = true;
    };
  };
  links = {
    "com.github.android" = {
      open = false;
    };
  };
  # The app ops Settings exposes that are explicitly granted right now.
  # Platform-internal ops are never dumped: android-enforce does not
  # manage them either.
  appops = {
    "com.whatsapp" = {
      RUN_ANY_IN_BACKGROUND = "allow";
    };
  };
}
