# Generated by `android-enforce --dump --dump-all` — the declared apps'
# full current state: every runtime permission they hold, notification
# access, the app ops that are explicitly granted and the link domains
# that open in the app. Applying it is a no-op; it *is* the phone.
#
# Every declared app is listed — one with nothing declared is an empty
# block — so the file is the whole install list, not only the configured
# part of it.
#
# Use it as:  apps = import ./android-app-state.nix;
{
  "ai.polycam" = {
    notifications.enabled = false;
  };
  "ani.aayush262.dartotsu" = { };
  "app.deglaze.prod" = {
    notifications.enabled = false;
  };
  "app.linear" = {
    notifications.enabled = false;
  };
  "app.revanced.manager.flutter" = {
    notifications.enabled = true;
  };
  "app.secanda.www" = {
    notifications.enabled = false;
  };
  "ch.admin.swisstopo" = {
    notifications.enabled = false;
  };
  "ch.agov.accessapp" = {
    notifications.enabled = false;
  };
  "ch.agrisano.agrisano" = { };
  "ch.bk.voteinfo" = {
    notifications.enabled = false;
  };
  "ch.medgate.threesixty.app" = {
    notifications.enabled = false;
  };
  "ch.migros.app" = {
    notifications.enabled = true;
  };
  "ch.pocketpc.nearbyglasses" = {
    permissions."android.permission.BLUETOOTH_CONNECT" = "allow";
    permissions."android.permission.BLUETOOTH_SCAN" = "allow";
    notifications.enabled = true;
  };
  "ch.sbb.mobile.android.preview" = {
    permissions."android.permission.ACCESS_FINE_LOCATION" = "allow";
    permissions."android.permission.BLUETOOTH_CONNECT" = "allow";
    permissions."android.permission.ACCESS_COARSE_LOCATION" = "allow";
    permissions."android.permission.ACTIVITY_RECOGNITION" = "allow";
    permissions."android.permission.BLUETOOTH_SCAN" = "allow";
    notifications.enabled = true;
  };
  "ch.stadt.sg.moapp" = {
    notifications.enabled = false;
  };
  "ch.threema.app" = {
    notifications.enabled = false;
  };
  "ch.viac.vorsorge3a" = { };
  "ch.wohnungssuche.wohnungssuche_app" = { };
  "com.Slack" = {
    notifications.enabled = false;
  };
  "com.Splitwise.SplitwiseMobile" = {
    notifications.enabled = false;
  };
  "com.abdurazaaqmohammed.AntiSplit" = { };
  "com.app.tgtg" = {
    notifications.enabled = false;
  };
  "com.bitwarden.authenticator" = {
    notifications.enabled = false;
  };
  "com.cashyou" = {
    notifications.enabled = false;
  };
  "com.chair.infinityblade" = { };
  "com.citypop.app" = {
    notifications.enabled = false;
  };
  "com.darkempire78.opencalculator" = { };
  "com.deniscerri.ytdl" = {
    notifications.enabled = false;
  };
  "com.dergoogler.mmrl" = {
    notifications.enabled = false;
  };
  "com.discord" = {
    permissions."android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
    notifications.enabled = true;
  };
  "com.emanuelef.remote_capture" = {
    notifications.enabled = false;
  };
  "com.eveningoutpost.dexdrip" = {
    permissions."android.permission.health.READ_RESTING_HEART_RATE" = "allow";
    permissions."android.permission.health.READ_ELEVATION_GAINED" = "allow";
    permissions."android.permission.READ_CALL_LOG" = "allow";
    permissions."android.permission.ACCESS_FINE_LOCATION" = "allow";
    permissions."android.permission.health.READ_HEART_RATE_VARIABILITY" = "allow";
    permissions."android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
    permissions."android.permission.health.READ_HYDRATION" = "allow";
    permissions."android.permission.health.READ_WHEELCHAIR_PUSHES" = "allow";
    permissions."android.permission.BLUETOOTH_CONNECT" = "allow";
    permissions."android.permission.health.READ_DISTANCE" = "allow";
    permissions."android.permission.health.WRITE_BLOOD_GLUCOSE" = "allow";
    permissions."android.permission.health.READ_TOTAL_CALORIES_BURNED" = "allow";
    permissions."android.permission.READ_EXTERNAL_STORAGE" = "allow";
    permissions."android.permission.health.READ_NUTRITION" = "allow";
    permissions."android.permission.ACCESS_COARSE_LOCATION" = "allow";
    permissions."android.permission.READ_PHONE_STATE" = "allow";
    permissions."android.permission.SEND_SMS" = "allow";
    permissions."android.permission.READ_MEDIA_IMAGES" = "allow";
    permissions."android.permission.CAMERA" = "allow";
    permissions."android.permission.READ_MEDIA_VIDEO" = "allow";
    permissions."android.permission.health.WRITE_NUTRITION" = "allow";
    permissions."android.permission.BLUETOOTH_ADVERTISE" = "allow";
    permissions."android.permission.health.READ_EXERCISE" = "allow";
    permissions."android.permission.GET_ACCOUNTS" = "allow";
    permissions."android.permission.health.READ_POWER" = "allow";
    permissions."android.permission.health.READ_SLEEP" = "allow";
    permissions."android.permission.health.READ_SPEED" = "allow";
    permissions."android.permission.health.READ_STEPS" = "allow";
    permissions."android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
    permissions."android.permission.health.READ_HEIGHT" = "allow";
    permissions."android.permission.health.READ_BLOOD_GLUCOSE" = "allow";
    permissions."android.permission.ACTIVITY_RECOGNITION" = "allow";
    permissions."android.permission.health.READ_FLOORS_CLIMBED" = "allow";
    permissions."android.permission.health.READ_WEIGHT" = "allow";
    permissions."android.permission.READ_CONTACTS" = "allow";
    permissions."android.permission.ACCESS_BACKGROUND_LOCATION" = "allow";
    permissions."android.permission.BLUETOOTH_SCAN" = "allow";
    permissions."android.permission.health.READ_HEART_RATE" = "allow";
    permissions."android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    notifications.enabled = true;
    notifications.listeners = [ "com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.services.UiBasedCollector" ];
  };
  "com.facebook.katana" = {
    notifications.enabled = false;
  };
  "com.facebook.pages.app" = {
    notifications.enabled = false;
  };
  "com.gamma.scan" = { };
  "com.ghisler.android.TotalCommander" = {
    notifications.enabled = false;
  };
  "com.github.android" = {
    notifications.enabled = true;
    links.open = false;
  };
  "com.goodreads" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.adm" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.books" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.chromecast.app" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.docs.editors.docs" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.docs.editors.sheets" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.fitness" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.healthdata" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.magazines" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.tasks" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.translate" = {
    notifications.enabled = false;
  };
  "com.google.android.apps.walletnfcrel" = {
    notifications.enabled = true;
  };
  "com.google.android.apps.youtube.creator" = {
    notifications.enabled = false;
  };
  "com.google.android.contactkeys" = { };
  "com.google.android.safetycore" = { };
  "com.google.android.verifier" = {
    notifications.enabled = false;
  };
  "com.google.ar.lens" = { };
  "com.instagram.android" = {
    notifications.enabled = false;
  };
  "com.instagram.barcelona" = {
    notifications.enabled = false;
  };
  "com.jndapp.cartoon.crayon.iconpack" = {
    notifications.enabled = false;
  };
  "com.knudge.me" = {
    notifications.enabled = false;
  };
  "com.lemon.lvoverseas" = {
    notifications.enabled = false;
  };
  "com.linkedin.android" = {
    notifications.enabled = false;
  };
  "com.marsvard.stickermakerforwhatsapp" = {
    notifications.enabled = false;
  };
  "com.mcdonalds.mobileapp" = {
    notifications.enabled = false;
  };
  "com.metrolist.music" = {
    notifications.enabled = true;
  };
  "com.microsoft.office.excel" = {
    notifications.enabled = true;
  };
  "com.microsoft.office.outlook" = {
    notifications.enabled = true;
  };
  "com.microsoft.office.word" = {
    notifications.enabled = true;
  };
  "com.microsoft.teams" = {
    notifications.enabled = false;
  };
  "com.nianticlabs.scaniverse" = {
    notifications.enabled = false;
  };
  "com.niksoftware.snapseed" = {
    notifications.enabled = false;
  };
  "com.nuvio.app" = {
    notifications.enabled = false;
  };
  "com.orailnoor.privatelm" = {
    notifications.enabled = false;
  };
  "com.pcapdroid.mitm" = { };
  "com.remarkable.mobile" = { };
  "com.revolut.revolut" = {
    notifications.enabled = false;
  };
  "com.rubenmayayo.lemmy" = {
    notifications.enabled = false;
  };
  "com.snapchat.android" = {
    notifications.enabled = false;
  };
  "com.ssaurel.nfcreader" = { };
  "com.stremio.one" = {
    notifications.enabled = false;
  };
  "com.sukisu.ultra" = {
    notifications.enabled = true;
  };
  "com.suno.android" = {
    notifications.enabled = false;
  };
  "com.tailscale.ipn" = {
    notifications.enabled = false;
  };
  "com.termux" = {
    permissions."android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
    permissions."android.permission.READ_EXTERNAL_STORAGE" = "allow";
    permissions."android.permission.READ_MEDIA_IMAGES" = "allow";
    permissions."android.permission.READ_MEDIA_VIDEO" = "allow";
    permissions."android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
    permissions."android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    notifications.enabled = true;
  };
  "com.termux.api" = {
    permissions."android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
    permissions."android.permission.READ_EXTERNAL_STORAGE" = "allow";
    permissions."android.permission.READ_MEDIA_IMAGES" = "allow";
    permissions."android.permission.READ_MEDIA_VIDEO" = "allow";
    permissions."android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
    permissions."android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    notifications.enabled = true;
    notifications.listeners = [ "com.termux.api/com.termux.api.apis.NotificationListAPI$NotificationService" ];
  };
  "com.tsng.hidemyapplist" = { };
  "com.ubs.Paymit.android" = {
    permissions."android.permission.ACCESS_FINE_LOCATION" = "allow";
    permissions."android.permission.ACCESS_COARSE_LOCATION" = "allow";
    permissions."android.permission.WRITE_CONTACTS" = "allow";
    permissions."android.permission.CAMERA" = "allow";
    permissions."android.permission.READ_CONTACTS" = "allow";
    notifications.enabled = true;
  };
  "com.ubs.swidK2Y.android" = {
    permissions."android.permission.CAMERA" = "allow";
    notifications.enabled = false;
  };
  "com.urbandroid.sleep" = {
    permissions."android.permission.ACTIVITY_RECOGNITION" = "allow";
    notifications.enabled = true;
  };
  "com.valvesoftware.android.steam.community" = {
    notifications.enabled = false;
  };
  "com.wakdev.wdnfc" = { };
  "com.watchguard.authpoint" = {
    notifications.enabled = false;
  };
  "com.whatsapp" = {
    permissions."android.permission.READ_CALL_LOG" = "allow";
    permissions."android.permission.ACCESS_FINE_LOCATION" = "allow";
    permissions."android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
    permissions."android.permission.ACCESS_COARSE_LOCATION" = "allow";
    permissions."android.permission.READ_PHONE_STATE" = "allow";
    permissions."android.permission.READ_MEDIA_IMAGES" = "allow";
    permissions."android.permission.WRITE_CONTACTS" = "allow";
    permissions."android.permission.CAMERA" = "allow";
    permissions."android.permission.READ_MEDIA_VIDEO" = "allow";
    permissions."android.permission.GET_ACCOUNTS" = "allow";
    permissions."android.permission.RECORD_AUDIO" = "allow";
    permissions."android.permission.READ_CONTACTS" = "allow";
    notifications.enabled = true;
    appops.RUN_ANY_IN_BACKGROUND = "allow";
  };
  "com.x8bit.bitwarden" = {
    permissions."android.permission.CAMERA" = "allow";
    notifications.enabled = true;
  };
  "com.xda.sa2ration" = {
    notifications.enabled = false;
  };
  "dantotsu.downloadAddon" = {
    notifications.enabled = false;
  };
  "dantotsu.torrentAddon" = {
    notifications.enabled = false;
  };
  "de.komoot.android" = {
    notifications.enabled = false;
  };
  "de.mm20.launcher2.release" = {
    permissions."android.permission.READ_CALENDAR" = "allow";
    permissions."android.permission.ACCESS_FINE_LOCATION" = "allow";
    permissions."android.permission.ACCESS_COARSE_LOCATION" = "allow";
    permissions."android.permission.READ_CONTACTS" = "allow";
    notifications.enabled = false;
    notifications.listeners = [ "de.mm20.launcher2.release/de.mm20.launcher2.notifications.NotificationService" ];
  };
  "dev.imranr.obtainium" = {
    notifications.enabled = false;
  };
  "droom.sleepIfUCan" = {
    notifications.enabled = false;
  };
  "eu.kanade.tachiyomi.animeextension.en.allanime" = { };
  "eu.kanade.tachiyomi.animeextension.en.allanimechi" = { };
  "eu.kanade.tachiyomi.animeextension.en.anikage" = { };
  "eu.kanade.tachiyomi.animeextension.en.anilist" = { };
  "eu.kanade.tachiyomi.animeextension.en.animenosub" = { };
  "eu.kanade.tachiyomi.animeextension.en.animepahe" = { };
  "eu.kanade.tachiyomi.animeextension.en.aniwatch" = { };
  "eu.kanade.tachiyomi.animeextension.en.aniwave" = { };
  "eu.kanade.tachiyomi.animeextension.en.kaido" = { };
  "eu.kanade.tachiyomi.animeextension.en.miruro" = { };
  "eu.kanade.tachiyomi.animeextension.en.nineanimetv" = { };
  "gr.nikolasspyr.integritycheck" = { };
  "io.element.android.x" = {
    notifications.enabled = false;
  };
  "io.ente.auth" = {
    notifications.enabled = false;
  };
  "io.keybase.ossifrage" = {
    notifications.enabled = false;
  };
  "me.kavishdevar.librepods" = {
    permissions."android.permission.ANSWER_PHONE_CALLS" = "allow";
    permissions."android.permission.BLUETOOTH_CONNECT" = "allow";
    permissions."android.permission.READ_PHONE_STATE" = "allow";
    permissions."android.permission.BLUETOOTH_ADVERTISE" = "allow";
    permissions."android.permission.BLUETOOTH_SCAN" = "allow";
    notifications.enabled = true;
  };
  "neth.iecal.curbox" = {
    notifications.enabled = false;
  };
  "org.adaway" = {
    notifications.enabled = false;
  };
  "org.mozilla.firefox" = {
    permissions."android.permission.ACCESS_FINE_LOCATION" = "allow";
    permissions."android.permission.ACCESS_COARSE_LOCATION" = "allow";
    permissions."android.permission.CAMERA" = "allow";
    notifications.enabled = true;
  };
  "org.proninyaroslav.libretorrent" = {
    notifications.enabled = false;
  };
  "org.telegram.messenger" = {
    notifications.enabled = false;
  };
  "org.thoughtcrime.securesms" = {
    notifications.enabled = false;
  };
  "org.torproject.android" = {
    notifications.enabled = false;
  };
  "org.videolan.vlc" = {
    notifications.enabled = false;
  };
  "tk.glucodata" = {
    permissions."android.permission.NEARBY_WIFI_DEVICES" = "allow";
    permissions."android.permission.BLUETOOTH_CONNECT" = "allow";
    permissions."android.permission.health.WRITE_BLOOD_GLUCOSE" = "allow";
    permissions."android.permission.CAMERA" = "allow";
    permissions."android.permission.BLUETOOTH_ADVERTISE" = "allow";
    permissions."android.permission.BLUETOOTH_SCAN" = "allow";
    notifications.enabled = true;
  };
  "za.co.lukestonehm.logicaldefence" = { };
}
