{
  # Generated by `android-enforce --dump` — the declared apps' current
  # runtime permissions (the ones you set) and notification access.
  permissions = {
    "ani.aayush262.dartotsu" = {
      "android.permission.READ_MEDIA_AUDIO" = "deny";
    };
    "ch.pocketpc.nearbyglasses" = {
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
    "ch.sbb.mobile.android.preview" = {
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.ACTIVITY_RECOGNITION" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
    "com.discord" = {
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "deny";
      "android.permission.READ_MEDIA_VIDEO" = "deny";
    };
    "com.eveningoutpost.dexdrip" = {
      "android.permission.health.READ_RESTING_HEART_RATE" = "allow";
      "android.permission.health.READ_ELEVATION_GAINED" = "allow";
      "android.permission.READ_CALL_LOG" = "allow";
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.health.READ_HEART_RATE_VARIABILITY" = "allow";
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.health.READ_HYDRATION" = "allow";
      "android.permission.health.READ_WHEELCHAIR_PUSHES" = "allow";
      "android.permission.health.READ_DISTANCE" = "allow";
      "android.permission.health.WRITE_BLOOD_GLUCOSE" = "allow";
      "android.permission.health.READ_TOTAL_CALORIES_BURNED" = "allow";
      "android.permission.READ_EXTERNAL_STORAGE" = "allow";
      "android.permission.health.READ_NUTRITION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.READ_PHONE_STATE" = "allow";
      "android.permission.SEND_SMS" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.READ_MEDIA_AUDIO" = "deny";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.health.WRITE_NUTRITION" = "allow";
      "android.permission.health.READ_EXERCISE" = "allow";
      "android.permission.GET_ACCOUNTS" = "allow";
      "android.permission.health.READ_POWER" = "allow";
      "android.permission.health.READ_SLEEP" = "allow";
      "android.permission.health.READ_SPEED" = "allow";
      "android.permission.health.READ_STEPS" = "allow";
      "android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
      "android.permission.health.READ_HEIGHT" = "allow";
      "android.permission.health.READ_BLOOD_GLUCOSE" = "allow";
      "android.permission.health.READ_FLOORS_CLIMBED" = "allow";
      "android.permission.health.READ_WEIGHT" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
      "android.permission.ACCESS_BACKGROUND_LOCATION" = "allow";
      "android.permission.health.READ_HEART_RATE" = "allow";
      "android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    };
    "com.termux" = {
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.READ_EXTERNAL_STORAGE" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.READ_MEDIA_AUDIO" = "deny";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
      "android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    };
    "com.termux.api" = {
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.READ_EXTERNAL_STORAGE" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.READ_MEDIA_AUDIO" = "deny";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.WRITE_EXTERNAL_STORAGE" = "allow";
      "android.permission.ACCESS_MEDIA_LOCATION" = "allow";
    };
    "com.ubs.Paymit.android" = {
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.WRITE_CONTACTS" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
    };
    "com.urbandroid.sleep" = {
      "android.permission.ACTIVITY_RECOGNITION" = "allow";
    };
    "com.whatsapp" = {
      "android.permission.READ_CALL_LOG" = "allow";
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.READ_PHONE_STATE" = "allow";
      "android.permission.READ_MEDIA_IMAGES" = "allow";
      "android.permission.WRITE_CONTACTS" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.READ_MEDIA_VIDEO" = "allow";
      "android.permission.GET_ACCOUNTS" = "allow";
      "android.permission.RECORD_AUDIO" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
    };
    "com.x8bit.bitwarden" = {
      "android.permission.CAMERA" = "allow";
    };
    "de.mm20.launcher2.release" = {
      "android.permission.READ_CALENDAR" = "allow";
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.READ_CONTACTS" = "allow";
    };
    "me.kavishdevar.librepods" = {
      "android.permission.ANSWER_PHONE_CALLS" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.READ_PHONE_STATE" = "allow";
      "android.permission.BLUETOOTH_ADVERTISE" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
    "org.mozilla.firefox" = {
      "android.permission.ACCESS_FINE_LOCATION" = "allow";
      "android.permission.ACCESS_COARSE_LOCATION" = "allow";
      "android.permission.CAMERA" = "allow";
    };
    "tk.glucodata" = {
      "android.permission.NEARBY_WIFI_DEVICES" = "allow";
      "android.permission.BLUETOOTH_CONNECT" = "allow";
      "android.permission.health.WRITE_BLOOD_GLUCOSE" = "allow";
      "android.permission.CAMERA" = "allow";
      "android.permission.BLUETOOTH_ADVERTISE" = "allow";
      "android.permission.BLUETOOTH_SCAN" = "allow";
    };
  };
  notifications = {
    "app.revanced.manager.flutter" = {
      enabled = true;
    };
    "ch.migros.app" = {
      enabled = true;
    };
    "ch.pocketpc.nearbyglasses" = {
      enabled = true;
    };
    "ch.sbb.mobile.android.preview" = {
      enabled = true;
    };
    "com.discord" = {
      enabled = true;
    };
    "com.eveningoutpost.dexdrip" = {
      enabled = true;
      listeners = [ "com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.services.UiBasedCollector" ];
    };
    "com.github.android" = {
      enabled = true;
    };
    "com.google.android.apps.walletnfcrel" = {
      enabled = true;
    };
    "com.microsoft.office.excel" = {
      enabled = true;
    };
    "com.microsoft.office.outlook" = {
      enabled = true;
    };
    "com.sukisu.ultra" = {
      enabled = true;
    };
    "com.termux" = {
      enabled = true;
    };
    "com.termux.api" = {
      enabled = true;
      listeners = [ "com.termux.api/com.termux.api.apis.NotificationListAPI$NotificationService" ];
    };
    "com.ubs.Paymit.android" = {
      enabled = true;
    };
    "com.urbandroid.sleep" = {
      enabled = true;
    };
    "com.whatsapp" = {
      enabled = true;
    };
    "com.x8bit.bitwarden" = {
      enabled = true;
    };
    "de.mm20.launcher2.release" = {
      listeners = [ "de.mm20.launcher2.release/de.mm20.launcher2.notifications.NotificationService" ];
    };
    "me.kavishdevar.librepods" = {
      enabled = true;
    };
    "org.mozilla.firefox" = {
      enabled = true;
    };
    "tk.glucodata" = {
      enabled = true;
    };
  };
}
