# -*- conf -*-

font=jetbrainsmono nerd font:size=12
dpi-aware=true
pad=10x10

[environment]

[bell]

[scrollback]

[url]

[cursor]
style=beam
blink=yes

[mouse]
hide-when-typing=yes

GENERATED_COLORS

[csd]

[key-bindings]

[search-bindings]

[url-bindings]

[text-bindings]

[mouse-bindings]

# vim: ft=dosini
